/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/challenges`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/oauthredirect`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/bot` | `/bot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/game-modes` | `/game-modes`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial/watch`; params?: Router.UnknownInputParams; } | { pathname: `/match/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/challenges`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/oauthredirect`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/bot` | `/bot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/game-modes` | `/game-modes`; params?: Router.UnknownOutputParams; } | { pathname: `/tutorial/watch`; params?: Router.UnknownOutputParams; } | { pathname: `/match/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/challenges${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/oauthredirect${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/bot${`?${string}` | `#${string}` | ''}` | `/bot${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/lobby${`?${string}` | `#${string}` | ''}` | `/lobby${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/game-modes${`?${string}` | `#${string}` | ''}` | `/game-modes${`?${string}` | `#${string}` | ''}` | `/tutorial/watch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/challenges`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/oauthredirect`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/bot` | `/bot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/game-modes` | `/game-modes`; params?: Router.UnknownInputParams; } | { pathname: `/tutorial/watch`; params?: Router.UnknownInputParams; } | `/match/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/match/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
